name: fly_ui
description: A new Flutter module project.

version: 1.1.0+2

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  unicons: ^2.1.1
  flutter_animator: ^3.2.0
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.7
  animations: ^2.0.7
  flutter_zoom_drawer: ^3.2.0
  paginate_firestore_plus: ^1.0.1+2

  app_configuration_service:
    git:
      url: git@github.com:niypoo/app_configuration_service.git
  loading_service:
    git:
      url: git@github.com:niypoo/loading_service.git
  launch_url_helper:
    git: 
      url: git@github.com:niypoo/launch_url_helper.git
  bottom_sheet_helper:
    git: 
      url: git@github.com:niypoo/bottom_sheet_helper.git
  localization_service:
    git: 
      url: git@github.com:niypoo/localization_service.git
  helpers:
    git: 
      url: git@github.com:niypoo/helpers.git
      
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
